name: CI-CD

on:
  push:
    branches: [ "main" ]  # or your production branch

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Deploy container
        run: |
          # Pull the newest image
          docker pull ghcr.io/${{ github.repository }}:latest
          # Stop old container (if running)
          docker stop card.runningdigitally.com || true
          docker rm card.runningdigitally.com || true
          # Run new container
          docker run -d --name card.runningdigitally.com \
            --restart always \
            --env-file=/home/satsur/.env.card.runningdigitally.com \
            -v card_access_data:/app/data
            -p 8080:8080 \
            ghcr.io/${{ github.repository }}:latest